name: PR Validation

on:
  pull_request:
    branches:
      - develop

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Run HTMLHint
        run: npx htmlhint "src/**/*.html"

      - name: Run Stylelint
        run: npx stylelint "styles/**/*.css"

  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Build with Parcel
        run: npx parcel build src/index.html --no-minify
